export const SECURITY_AUTHENTICATED = 'SECURITY_AUTHENTICATED';
export const SECURITY_UNAUTHENTICATED = 'SECURITY_UNAUTHENTICATED';
export const SECURITY_AUTHENTICATION_ERROR = 'SECURITY_AUTHENTICATION_ERROR';
